Axios Interceptor Functionality
irtazazulfiqar/News-App pull request #9
Opened 2024-08-30 06:23 UTC by irtazazulfiqar

2024-09-05 14:49 UTC, m-shayan-ahmad requested changes

2024-09-05 14:49 UTC, m-shayan-ahmad commented on frontend/src/pages/ArticleDetails.js
>            }
Same question here. Calling API in `try` block will always move to `catch` when the API returns non-success status codes.

2024-09-06 07:18 UTC, irtazazulfiqar commented on frontend/src/pages/Dashboard.js
> +    if (axios.isCancel(error)) {
Sometimes we  might want to cancel a network request if it becomes irrelevant, axios allows to cancel a request, and axios.isCancel(error) checks if the error was specifically due to such a cancellation. It happens in a case, user is making unnecessary requests or spamming , like spamming with requests even when data is not rendered:

Use-Case: User tries to spam different dates continuously clicking dates on calendar turn by turn.

2024-09-06 07:18 UTC, irtazazulfiqar commented on frontend/src/components/Calender.js
> +  }, [selectedDate, onDateChange]);
yes reviewed it properly, it is working fine too.

2024-09-06 10:42 UTC, m-shayan-ahmad commented on frontend/src/components/Calender.js
>            // Ensure dates are parsed correctly as Date objects
Do we need to check status is 200 here?

2024-09-06 10:42 UTC, m-shayan-ahmad commented on frontend/src/components/Calender.js
>            // Ensure dates are parsed correctly as Date objects
Also, update all other places.

2024-09-06 10:42 UTC, m-shayan-ahmad commented on frontend/src/components/Calender.js
> +  }, [selectedDate, onDateChange]);
Do you think we need this useEffect? I have already commented the same suggestion in previous PR.

2024-09-06 10:44 UTC, m-shayan-ahmad commented on frontend/src/pages/Dashboard.js
> +    if (axios.isCancel(error)) {
The request should not be cancelled in this case. We should return a max request limit error in that case.

2024-09-06 11:22 UTC, irtazazulfiqar commented on frontend/src/pages/Dashboard.js
> +    if (axios.isCancel(error)) {
yes we can also do it by response status code 429 which is server response code for handling too much requests

2024-09-06 11:57 UTC, m-shayan-ahmad approved these changes

2024-09-06 11:57 UTC, m-shayan-ahmad commented on frontend/src/pages/Dashboard.js
> +        setError('You have exceeded the maximum number of requests. Please try again later.');
We don't need to show this error to the user because it's a technical issue. You can just say that "Something went wrong!" here.

2024-09-06 12:00 UTC, merged